/* Generated By:JJTree: Do not edit this line. AttrStmt.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.dancingbear.graphbrowser.importer.dotparser;

public
class AttrStmt extends SimpleNode {
  public AttrStmt(int id) {
    super(id);
  }

  public AttrStmt(DOTParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=397e4b52e9c00a298de53a5d494287f4 (do not edit this line) */
