/* Generated By:JJTree: Do not edit this line. AttrList.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.dancingbear.graphbrowser.importer.dotparser;

public
class AttrList extends SimpleNode {
  public AttrList(int id) {
    super(id);
  }

  public AttrList(DOTParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b28da979793bc6b7c2628d259d1b1adc (do not edit this line) */
