/* Generated By:JavaCC: Do not edit this line. DOTParserTreeConstants.java Version 4.2 */
package org.dancingbear.graphbrowser.importer.dotparser;

public interface DOTParserTreeConstants
{
  public int JJTPARSE = 0;
  public int JJTGRAPH = 1;
  public int JJTSTMTLIST = 2;
  public int JJTSTMT = 3;
  public int JJTATTRSTMT = 4;
  public int JJTATTRLIST = 5;
  public int JJTATTR = 6;
  public int JJTIDEQSTMT = 7;
  public int JJTNODESTMT = 8;
  public int JJTNODEID = 9;
  public int JJTPORT = 10;
  public int JJTEDGESTMT = 11;
  public int JJTEDGERHS = 12;
  public int JJTEDGEOP = 13;
  public int JJTSUBGRAPH = 14;


  public String[] jjtNodeName = {
    "Parse",
    "Graph",
    "StmtList",
    "Stmt",
    "AttrStmt",
    "AttrList",
    "Attr",
    "IdeqStmt",
    "NodeStmt",
    "NodeId",
    "Port",
    "EdgeStmt",
    "EdgeRHS",
    "EdgeOp",
    "Subgraph",
  };
}
/* JavaCC - OriginalChecksum=391ea3d6df898188e3fb61cbb59e75a5 (do not edit this line) */
