/* Generated By:JavaCC: Do not edit this line. DOTParserVisitor.java Version 4.2 */
package org.dancingbear.graphbrowser.importer.dotparser;

public interface DOTParserVisitor {
    public Object visit(SimpleNode node, Object data);

    public Object visit(Parse node, Object data);

    public Object visit(Graph node, Object data);

    public Object visit(StmtList node, Object data);

    public Object visit(Stmt node, Object data);

    public Object visit(AttrStmt node, Object data);

    public Object visit(AttrList node, Object data);

    public Object visit(Attr node, Object data);

    public Object visit(IdeqStmt node, Object data);

    public Object visit(NodeStmt node, Object data);

    public Object visit(NodeId node, Object data);

    public Object visit(Port node, Object data);

    public Object visit(EdgeStmt node, Object data);

    public Object visit(EdgeRHS node, Object data);

    public Object visit(EdgeOp node, Object data);

    public Object visit(Subgraph node, Object data);
}
/*
 * JavaCC - OriginalChecksum=858b20667e8d4b7ac905ee90db0c75b6 (do not edit this
 * line)
 */
