/* Generated By:JJTree&JavaCC: Do not edit this line. DOTParserConstants.java */
package org.dancingbear.graphbrowser.importer.dotparser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface DOTParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 9;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 10;
  /** RegularExpression Id. */
  int DIGRAPH = 12;
  /** RegularExpression Id. */
  int EDGE = 13;
  /** RegularExpression Id. */
  int GRAPH = 14;
  /** RegularExpression Id. */
  int NODE = 15;
  /** RegularExpression Id. */
  int STRICT = 16;
  /** RegularExpression Id. */
  int SUBGRAPH = 17;
  /** RegularExpression Id. */
  int EQ = 18;
  /** RegularExpression Id. */
  int LBRACE = 19;
  /** RegularExpression Id. */
  int RBRACE = 20;
  /** RegularExpression Id. */
  int EDGE_UNDIRECTED = 21;
  /** RegularExpression Id. */
  int EDGE_DIRECTED = 22;
  /** RegularExpression Id. */
  int LBRACKET = 23;
  /** RegularExpression Id. */
  int RBRACKET = 24;
  /** RegularExpression Id. */
  int COMMA = 25;
  /** RegularExpression Id. */
  int SEMICOLON = 26;
  /** RegularExpression Id. */
  int COLON = 27;
  /** RegularExpression Id. */
  int LRBRACKET = 28;
  /** RegularExpression Id. */
  int RRBRACKET = 29;
  /** RegularExpression Id. */
  int AT = 30;
  /** RegularExpression Id. */
  int ID = 31;
  /** RegularExpression Id. */
  int HTML = 32;
  /** RegularExpression Id. */
  int $HtmlString = 33;
  /** RegularExpression Id. */
  int $BaseChar = 34;
  /** RegularExpression Id. */
  int $Ideographic = 35;
  /** RegularExpression Id. */
  int CombiningChar = 36;
  /** RegularExpression Id. */
  int $Digit = 37;
  /** RegularExpression Id. */
  int Extender = 38;
  /** RegularExpression Id. */
  int $EscapedCharacter = 39;
  /** RegularExpression Id. */
  int $NotWhitespaceNotQuoteNotEscape = 40;
  /** RegularExpression Id. */
  int $Letter = 41;
  /** RegularExpression Id. */
  int $Number = 42;
  /** RegularExpression Id. */
  int $UnquotedString = 43;
  /** RegularExpression Id. */
  int $QuotedString = 44;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_SINGLE_LINE_COMMENT = 1;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 2;
  /** Lexical state. */
  int IN_C_OUTPUT = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"//\"",
    "\"/*\"",
    "\"#\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "<token of kind 11>",
    "\"digraph\"",
    "\"edge\"",
    "\"graph\"",
    "\"node\"",
    "\"strict\"",
    "\"subgraph\"",
    "\"=\"",
    "\"{\"",
    "\"}\"",
    "\"--\"",
    "\"->\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\";\"",
    "\":\"",
    "\"(\"",
    "\")\"",
    "\"@\"",
    "<ID>",
    "<HTML>",
    "<$HtmlString>",
    "<$BaseChar>",
    "<$Ideographic>",
    "<CombiningChar>",
    "<$Digit>",
    "<Extender>",
    "<$EscapedCharacter>",
    "<$NotWhitespaceNotQuoteNotEscape>",
    "<$Letter>",
    "<$Number>",
    "<$UnquotedString>",
    "<$QuotedString>",
  };

}
