/* Generated By:JJTree: Do not edit this line. EdgeRHS.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.dancingbear.graphbrowser.importer.dotparser;

public
class EdgeRHS extends SimpleNode {
  public EdgeRHS(int id) {
    super(id);
  }

  public EdgeRHS(DOTParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=947b87aba5825ca6bb1c49bb579c5927 (do not edit this line) */
