/* Generated By:JJTree: Do not edit this line. EdgeStmt.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.dancingbear.graphbrowser.importer.dotparser;

public
class EdgeStmt extends SimpleNode {
  public EdgeStmt(int id) {
    super(id);
  }

  public EdgeStmt(DOTParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8dfe4761c00d5795e10cb81397c33cee (do not edit this line) */
