/* Generated By:JJTree: Do not edit this line. EdgeOp.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.dancingbear.graphbrowser.importer.dotparser;

public
class EdgeOp extends SimpleNode {
  public EdgeOp(int id) {
    super(id);
  }

  public EdgeOp(DOTParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=efeea85a7751bbb36ce984a7d8a1d7f4 (do not edit this line) */
