/* Generated By:JJTree: Do not edit this line. Graph.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.dancingbear.graphbrowser.importer.dotparser;

public
class Graph extends SimpleNode {
  public Graph(int id) {
    super(id);
  }

  public Graph(DOTParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=66228178135b958b89d352ff09f23f8b (do not edit this line) */
