/* Generated By:JJTree: Do not edit this line. IdeqStmt.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.dancingbear.graphbrowser.importer.dotparser;

public
class IdeqStmt extends SimpleNode {
  public IdeqStmt(int id) {
    super(id);
  }

  public IdeqStmt(DOTParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0f4236f4cc324d7ff713a035c506dad2 (do not edit this line) */
