/* Generated By:JJTree: Do not edit this line. NodeStmt.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.dancingbear.graphbrowser.importer.dotparser;

public
class NodeStmt extends SimpleNode {
  public NodeStmt(int id) {
    super(id);
  }

  public NodeStmt(DOTParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2ee5df54b6e2f243136802551c0168ba (do not edit this line) */
