/* Generated By:JJTree: Do not edit this line. NodeId.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.dancingbear.graphbrowser.importer.dotparser;

public
class NodeId extends SimpleNode {
  public NodeId(int id) {
    super(id);
  }

  public NodeId(DOTParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=68308e31c9f383800bcefaa73580a9de (do not edit this line) */
