/* Generated By:JJTree: Do not edit this line. Parse.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.dancingbear.graphbrowser.importer.dotparser;

public
class Parse extends SimpleNode {
  public Parse(int id) {
    super(id);
  }

  public Parse(DOTParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=165e2a017e2d44e0473e2e73b72a2b7e (do not edit this line) */
