/* Generated By:JJTree: Do not edit this line. Port.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.dancingbear.graphbrowser.importer.dotparser;

public
class Port extends SimpleNode {
  public Port(int id) {
    super(id);
  }

  public Port(DOTParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2a5eb389572c8e1174f4ba58e2801955 (do not edit this line) */
