/* Generated By:JJTree: Do not edit this line. Stmt.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.dancingbear.graphbrowser.importer.dotparser;

public
class Stmt extends SimpleNode {
  public Stmt(int id) {
    super(id);
  }

  public Stmt(DOTParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e0abda417ea98b2d1acf72a327c4f896 (do not edit this line) */
