/* Generated By:JJTree: Do not edit this line. StmtList.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.dancingbear.graphbrowser.importer.dotparser;

public
class StmtList extends SimpleNode {
  public StmtList(int id) {
    super(id);
  }

  public StmtList(DOTParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=037e35f8f365f0f9f34e8475c1619c21 (do not edit this line) */
