/* Generated By:JJTree: Do not edit this line. Subgraph.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.dancingbear.graphbrowser.importer.dotparser;

public
class Subgraph extends SimpleNode {
  public Subgraph(int id) {
    super(id);
  }

  public Subgraph(DOTParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=afc3cbe55f58f15e042e2eb70a2cdf6b (do not edit this line) */
